# Generated by Django 2.0.2 on 2019-06-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=60)),
                ('experience', models.CharField(max_length=60)),
                ('salary', models.CharField(max_length=60)),
                ('skillsrequired', models.TextField(max_length=60)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
    ]
