# Generated by Django 2.2.2 on 2019-06-27 06:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('city', models.CharField(default='', max_length=50)),
                ('tenth_marks', models.IntegerField(default='')),
                ('twelfth_marks', models.IntegerField(default='')),
                ('course', models.CharField(default='', max_length=50)),
                ('college_name', models.CharField(default='', max_length=100)),
                ('stream', models.CharField(default='', max_length=50)),
                ('graduation_year', models.IntegerField(default='')),
                ('is_valid', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
