# Generated by Django 2.2.2 on 2019-06-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile_number', models.IntegerField(default=2)),
                ('tenth_marks', models.CharField(default='', max_length=50)),
                ('twelfth_marks', models.CharField(default='', max_length=50)),
                ('grad_year', models.IntegerField(default='')),
            ],
        ),
    ]
