# Generated by Django 2.2.2 on 2019-06-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('details', models.TextField()),
            ],
        ),
    ]
