# Generated by Django 2.2.2 on 2019-06-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='mobile_number',
            field=models.IntegerField(default=''),
        ),
    ]
